### ISSUE TITLE
Consider rnmapbox instead of react-native-maps

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#498]
Can be used with expo development builds https://github.com/rnmapbox/maps

Community-maintained, though seems fairly active. Another alternative is the maplibre-gl fork: https://github.com/maplibre/maplibre-gl-native … Which after reviewing things seems like our only free option here.

~~I think rnmapbox can be used for free by us, given that we could use our own tiles (in the “styles” param and just exclude a map api key, and i don’t think we need their other API services. But I’m still trying to confirm that and will edit this post appropriately.~~

**Problems with react-native-maps**

Main issues I can think of right now are:

- Android custom map marker performance. We’re still showing default map markers in android, which is lame.
- The “Refresh this area” function. I don’t really dislike this function, but overall I think it would be ideal to have beautiful refreshing when the map is moved.

**Approach**

Ideally we would “test the waters” without having to put a ton of effort into it. Many of the concepts - mapview, callout, etc - should be the same. But still I assume it will require a decent amount of effort for a working POC. From there we can evaluate 1) if it’s really free! and 2) if it solves the above issues and seems smooth.

**Comment by RyanTG** [comment]
Initial branch: https://github.com/pinballmap/pbm-react/tree/mapbox

Note that the commit contains a lot of commented code (a mix of old code just to compare, and new things I tried but didn't succeed at) and also console logs.

Also note that this requires a development build.

Docs are found here https://github.com/rnmapbox/maps/blob/main/docs/MapView.md
If you search for help, you may come across the repo `nitaliano/react-native-mapbox-gl`. That is the old version of this same package, so many of those issues can still be useful.

One of the big things I am doing "wrong" here is the use of `Mapview.PointAnnotation` to display markers, as well as Callout for the callout. PointAnnotation has been deprecated for like 4 years. The new thing is ShapeSource + SymbolLayer, but it's quite complex! I barely understand it, and there aren't a ton of examples. **Actually** looking at the docs with fresh eyes right now, maybe ShapeSource is only for polylines and whatnot, so we would not use it, and only use SymbolLayer. That might simplify things. https://github.com/rnmapbox/maps/blob/main/docs/SymbolLayer.md

The big question I had with ShapeSource/SymbolLayer is "where do we put the coordinates for each symbol?" The answer seems to be that the data must be formatted as GeoJSON. So I followed https://stackoverflow.com/a/52917510 and tried constructing geoJSON from the API response. Seems crazy...

more discussion:
`https://github.com/rnmapbox/maps/issues/532#issuecomment-580347090`

Current branch status:

### WORKING
- Filtering
- Map themes
- Refresh (the `getVisibleBounds()` stuff that seems to work for me: https://stackoverflow.com/a/73406791)
- locationDetails map!

### NOT WORKING
- Initial map load (might be inconsistent - sometimes locations initially load?)
- Initial map zoom (when I set this in Mapview.Camera, it caused the map to zoom back to this zoom level after each time you zoom in/out - but I didn't really dig into this)
- Search (map does not go to new region and does not load new locations)
- OnPress on Callouts (again, it seems to be recommended to use SymbolLayer and _not_ Callout)
- user location dot
- User location button (sometimes does something?)

### NEEDS WORK
- If you are zoomed far out and pan the map, the pan "nudges" up after you stop panning. I did not explore why.
- Max Zoom seems to work inconsistently and/or incorrectly.
- Callout positioning (I didn't spend much time on this)
- Heart icons (just using pink dots for now. Images apparently do not work within `PointAnnotation`, but again, SymbolLayer is recommended instead).

**Comment by RyanTG** [comment]
Trying to track remaining issues:

- [ ] Map nudges up when you click Refresh while zoomed really far out
- [ ] await 500 is causing a flash when you click my location
- [ ] marker stuff
- [ ] Bottom sheet: include some machines?

I also want to think about:
- Bottom sheet background
- How the bottom sheet covers up the refresh button

**Comment by bpoore** [comment]
Fixed both map moving issues. Added the logic for [different colors for markers](https://github.com/pinballmap/pbm-react/commit/902d4dcdfc2ebb3835e13d198677b92f1553e009) depending on context. I assume if a marker is selected it takes precedence for the color, then if hearted and otherwise default. I put hideous colors in for now, so have fun picking what we want for the real thing 😄 We can play with custom shapes and sizes for the selected marker / fave locations depending on what you're feeling.

**Comment by RyanTG** [comment]
Issues discovered while beta testing:

- [ ] Move the map away from your location, refresh. Go to the Filter screen, do not choose anything, and then go back to map, the results on the map disappear and the results load "near you" (if you pan the map back to yourself you'll see them there).
- [ ] Orientation is not fixed to portrait.
